In [1]:
import numpy as np

### Input array

In [3]:
X = np.array([[1, 1],
            [1, 2],
            [1, 3]])

In [5]:
X

array([[1, 1],
       [1, 2],
       [1, 3]])

In [7]:
X.shape

(3, 2)

### Target variable

In [9]:
Y = np.array([2, 3, 5])

In [11]:
Y.shape

(3,)

In [13]:
Y

array([2, 3, 5])

In [ ]:
# ((X.T).X )^-1 . (X.T.y)

In [15]:
X.T

array([[1, 1, 1],
       [1, 2, 3]])

In [17]:
X.T @ X

array([[ 3,  6],
       [ 6, 14]])

In [29]:
X.T @ Y

array([10, 23])

In [21]:
np.linalg.inv(X.T @ X) @ (X.T @ Y)

array([0.33333333, 1.5       ])

In [ ]:
intercept -> 0.33 
slope -> 1.5 

In [ ]:
m = 1.5 #slope
b = 0.33 #intercept

In [ ]:
y = mx + b
y = 1.5 (x) + 0.33