In [1]:
import numpy as np
import pandas as pd
import sklearn #scikit-learn
import os

In [2]:
os.getcwd()

'C:\\Users\\moham\\OneDrive - University of Central Missouri\\Desktop\\Imran\\Training\\Inceptez-24\\Kaggle'

### Reading the dataset

In [4]:
dataset = pd.read_csv('Data.csv')

In [5]:
# pd.read_csv(r'C:\Users\moham\OneDrive - University of Central Missouri\Desktop\Imran\Training\Data.csv')

In [6]:
dataset[:3]

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No

In [7]:
df = pd.DataFrame(dataset)

In [8]:
df[:3]

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No

In [9]:
df.shape

(10, 4)

In [10]:
X = df.iloc[:, :-1].values #independent variables

In [11]:
y = df.iloc[:, -1].values

In [12]:
X1 = df.iloc[:, :-1]
y1 = df.iloc[:, -1]

In [13]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [14]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [15]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [16]:
df1 = df.copy()

In [17]:
df1.shape #Before

(10, 4)

In [18]:
df1.dropna(inplace = True)

In [19]:
df1.shape #After

(8, 4)

In [20]:
df2 = df.copy()

In [21]:
df2

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [22]:
df2[['Age', 'Salary']] = df2[['Age', 'Salary']].fillna(df2[['Age', 'Salary']].mean())

In [23]:
df2['Age'].mean(), df2['Salary'].mean()

(38.77777777777778, 63777.777777777774)

In [24]:
df2

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [25]:
df2.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [26]:
# (37 + 38)/2

In [27]:
df2['Age'].fillna(45)

0    44.000000
1    27.000000
2    30.000000
3    38.000000
4    40.000000
5    35.000000
6    38.777778
7    48.000000
8    50.000000
9    37.000000
Name: Age, dtype: float64

In [28]:
from sklearn.impute import SimpleImputer

In [29]:
# my_name = SimpleImputer(missing_values=np.nan, strategy='median')

In [30]:
impute = SimpleImputer(missing_values=np.nan, strategy='median')
impute.fit(X[:, 1:3])
X[:, 1:3] = impute.transform(X[:, 1:3])


# X[:, 1:3] = impute.fit_transform(X[:, 1:3])

In [31]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding

In [33]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [34]:
# !pip install scikit-learn

In [35]:
ct = ColumnTransformer(transformers=[('encoding', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [36]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [37]:
# ColumnTransformer?

In [38]:
df2

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [39]:
df2[:3]

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No

In [40]:
pd.get_dummies(df2, dtype=int)

Age        Salary  Country_France  Country_Germany  Country_Spain  \
0  44.000000  72000.000000               1                0              0   
1  27.000000  48000.000000               0                0              1   
2  30.000000  54000.000000               0                1              0   
3  38.000000  61000.000000               0                0              1   
4  40.000000  63777.777778               0                1              0   
5  35.000000  58000.000000               1                0              0   
6  38.777778  52000.000000               0                0              1   
7  48.000000  79000.000000               1                0              0   
8  50.000000  83000.000000               0                1              0   
9  37.000000  67000.000000               1                0              0   

   Purchased_No  Purchased_Yes  
0             1              0  
1             0              1  
2             1              0  
3             1              0  
4             0              1  
5             0              1  
6             1              0  
7             0              1  
8             1              0  
9             0              1

In [41]:
# pd.get_dummies?

In [42]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [43]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [44]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [45]:
df2_temp = df2.iloc[1:, :]

In [46]:
y1_temp = df2_temp.iloc[:, -1]

In [47]:
print(y1_temp)

1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


In [48]:
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
y_temp = le.fit_transform(y1_temp)

In [49]:
print(y_temp)

[1 0 0 1 1 0 1 0 1]


In [50]:
print(X), print(y)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1 0 1]


(None, None)

In [51]:
X.shape

(10, 5)

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [54]:
print(X_train)

[[0.0 0.0 1.0 38.0 52000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [55]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [56]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [57]:
print(y_test)

[0 1]


In [58]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [59]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()

In [60]:
X_train[:, 3:] = mm.fit_transform(X_train[:, 3:])
X_test[:, 3:] =  mm.transform(X_test[:, 3:])

In [61]:
print(X_train[:, 3:])

[[0.4782608695652175 0.11428571428571432]
 [0.5652173913043479 0.37142857142857144]
 [0.7391304347826089 0.6857142857142855]
 [0.4782608695652175 0.37142857142857144]
 [0.0 0.0]
 [0.9130434782608696 0.8857142857142857]
 [1.0 1.0]
 [0.34782608695652173 0.2857142857142856]]


In [136]:
print(X_test[:, 3:])

[[-1.447149210584843 -0.8727355967528773]
 [-0.43414476317545264 0.2341485747385766]]


In [63]:
df2

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [64]:
from sklearn.preprocessing import StandardScaler
sta = StandardScaler()

In [65]:
X_train[:, 3:] = sta.fit_transform(X_train[:, 3:])
X_test[:, 3:] =  sta.transform(X_test[:, 3:])

In [66]:
print(X_train[:, 3:])

[[-0.2894298421169684 -1.0430254692900243]
 [0.0 -0.2767210428728635]
 [0.5788596842339376 0.6598732560814435]
 [-0.2894298421169684 -0.2767210428728635]
 [-1.8812939737602963 -1.383605214364318]
 [1.1577193684678744 1.255887809961458]
 [1.447149210584843 1.5964675550357519]
 [-0.7235746052924218 -0.5321558516785841]]


In [138]:
print(X_test[:, 3:])

[[-1.447149210584843 -0.8727355967528773]
 [-0.43414476317545264 0.2341485747385766]]
